"""Core cross-cutting facilities: config, logging, errors, IDs, versioning, constants."""

from contexttrading.core.config import (
    AIConfig,
    APIConfig,
    EngineConfig,
    LoggingConfig,
    SessionConfig,
    Settings,
    StorageConfig,
    get_settings,
)
from contexttrading.core.constants import (
    FLOAT_ABS_TOL,
    FLOAT_REL_TOL,
    LiquidityPoolKind,
    LiquiditySide,
    MitigationStatus,
    SessionName,
    StructureBreakClass,
    StructureBreakSignificance,
    StructureBreakType,
    SwingType,
    Timeframe,
    TrendDirection,
    ZoneType,
)
from contexttrading.core.errors import (
    AIProviderError,
    AnalysisError,
    APIError,
    BacktestError,
    ConfigurationError,
    ContextTradingError,
    DataError,
    DataGapError,
    InsufficientDataError,
    SchemaVersionError,
    ValidationError,
)
from contexttrading.core.ids import canonical_json, content_hash, deterministic_id, new_run_id
from contexttrading.core.logging import BoundLogger, configure_logging, get_logger
from contexttrading.core.versioning import (
    CURRENT_SCHEMA_VERSIONS,
    is_compatible,
    major_of,
    parse_version,
)

__all__ = [
    "CURRENT_SCHEMA_VERSIONS",
    "FLOAT_ABS_TOL",
    "FLOAT_REL_TOL",
    "AIConfig",
    "AIProviderError",
    "APIConfig",
    "APIError",
    "AnalysisError",
    "BacktestError",
    "BoundLogger",
    "ConfigurationError",
    "ContextTradingError",
    "DataError",
    "DataGapError",
    "EngineConfig",
    "InsufficientDataError",
    "LiquidityPoolKind",
    "LiquiditySide",
    "LoggingConfig",
    "MitigationStatus",
    "SchemaVersionError",
    "SessionConfig",
    "SessionName",
    "Settings",
    "StorageConfig",
    "StructureBreakClass",
    "StructureBreakSignificance",
    "StructureBreakType",
    "SwingType",
    "Timeframe",
    "TrendDirection",
    "ValidationError",
    "ZoneType",
    "canonical_json",
    "configure_logging",
    "content_hash",
    "deterministic_id",
    "get_logger",
    "get_settings",
    "is_compatible",
    "major_of",
    "new_run_id",
    "parse_version",
]
